"""HTF §4-L — Export to proof-assistant Lean 4 skeleton format.

Converts HTF certificates and structural reports to Lean 4 source files
containing:
* Namespace and import declarations.
* ``structure`` definitions mirroring HTF's ``Certificate`` and ``StructureReport``.
* ``theorem`` statements for variational bounds, Temple lower bounds, and
  structural properties, annotated with the numeric evidence from HTF.
* ``#check`` and ``#eval`` statements for lightweight machine-readable verification.
* ``sorry`` stubs where a full Lean proof is required (marked ``[研究]``).

The generated files are **valid Lean 4 syntax** that load without errors when
``import Mathlib`` is available; every ``sorry`` is a clearly labelled proof
obligation for a human Lean expert.

Provides
--------
* ``certificate_to_lean``          — format a legacy ``Certificate`` as a Lean ``theorem``.
* ``rayleigh_certificate_to_lean`` — format a ``RayleighCertificate`` (schema v2) correctly.
* ``DiagramToLean``      — express an HTF ``Diagram``'s type in Lean 4 syntax.
* ``GapReportToLean``    — gap bounds as Lean theorem statements.
* ``LeanExporter``       — collect items and write a complete ``.lean`` file.
* ``export_lean``        — one-shot helper: export a list of items to a path.

Honest scope
------------
* Generated theorems use ``sorry``; actual Lean proofs are ``[研究]``.
* The Lean 4 encoding of string-diagram category theory requires Mathlib's
  ``CategoryTheory`` library and is non-trivial; stubs use simplified types.
* No Lean server is invoked; HTF does not verify the generated file.
  Use ``lake build`` or ``lean --run`` externally to type-check.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ────────────────────── Lean 4 source builder ────────────────────────────

_LEAN_HEADER = """\
-- Auto-generated by HTF (Holographic Tensor Framework) §4-L
-- Every `sorry` is a proof obligation for a human Lean expert.
-- Requires: `import Mathlib` or `import Mathlib.Tactic`
-- License: MIT

import Mathlib.Tactic
import Mathlib.Analysis.InnerProductSpace.Basic

namespace HTF
"""

_LEAN_FOOTER = """\

end HTF
"""

_LEAN_BASE_DEFS = """\
/-- A floating-point interval representing a certified numeric result (legacy Certificate). -/
structure CertInterval where
  /-- Midpoint of the interval. -/
  mid   : Float
  /-- Radius (one-sided error bound); result lies in [mid − rad, mid + rad]. -/
  rad   : Float
  /-- Mode: "certified" means the interval is a rigorous FP-rounding bound. -/
  mode  : String

/-- Rayleigh Certificate v2 interval (lower/upper endpoint form, schema rayleigh-cert/v2). -/
structure RayleighInterval where
  /-- Certified lower endpoint of the Rayleigh quotient interval. -/
  lower    : Float
  /-- Certified upper endpoint; E_0 ≤ upper by Rayleigh-Ritz. -/
  upper    : Float
  /-- Midpoint = (lower + upper) / 2 (informational). -/
  midpoint : Float
  /-- Outward-rounded radius; [midpoint − radius, midpoint + radius] ⊆ [lower, upper]. -/
  radius   : Float
  /-- Backend: "flint-arb/prec=128", "flint-acb/prec=128", or "numpy-float". -/
  backend  : String

/-- Proof-carrying structural property report. -/
structure StructReport where
  property : String
  passed   : Bool
  defect   : Float
  tol      : Float

"""


def _lean_float(x: float) -> str:
    """Format a float for Lean: use scientific notation for very small/large values."""
    if x == 0.0:
        return "(0.0 : Float)"
    return f"({x:.15g} : Float)"


def _lean_string(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


# ────────────────────── Certificate → Lean ───────────────────────────────

def certificate_to_lean(cert: Any, name: str = "bound") -> str:
    """Convert an HTF ``Certificate`` to a Lean 4 declaration block.

    Parameters
    ----------
    cert : a ``Certificate`` object (from ``htf.certificate``).
    name : Lean identifier for the generated definition.

    Returns
    -------
    Lean 4 source string containing a ``def`` and an associated ``theorem``.
    """
    mid  = float(cert.result)
    rad  = float(cert.error_bound) if cert.error_bound is not None else 0.0
    mode = str(cert.mode)
    notes = getattr(cert, "notes", "") or ""

    lines = [
        f"-- HTF Certificate: {_lean_string(notes)}",
        f"def {name}_interval : CertInterval :=",
        f"  {{ mid  := {_lean_float(mid)},",
        f"    rad  := {_lean_float(rad)},",
        f"    mode := {_lean_string(mode)} }}",
        "",
        f"-- The true value V satisfies: {name}_interval.mid - {name}_interval.rad ≤ V",
        f"-- ≤ {name}_interval.mid + {name}_interval.rad",
        f"theorem {name}_upper_bound (V : ℝ) :",
        f"    V ≥ ({mid:.15g} : ℝ) - ({rad:.15g} : ℝ) := by",
        "  -- TODO: formalise HTF certified contraction proof [研究]",
        "  sorry",
        "",
    ]
    return "\n".join(lines)


# ────────────────────── RayleighCertificate (v2) → Lean ──────────────────

def rayleigh_certificate_to_lean(cert: Any, name: str = "rayleigh_bound") -> str:
    """Convert an HTF ``RayleighCertificate`` (schema v2) to a Lean 4 declaration block.

    Parameters
    ----------
    cert : a ``RayleighCertificate`` from ``htf.rayleigh_cert`` (schema rayleigh-cert/v2).
           Fields used: ``lower``, ``upper``, ``midpoint``, ``radius``, ``backend``,
           ``claim``, ``input_digest``, ``schema_version``.
    name : Lean identifier prefix.
    """
    lower    = float(cert.lower)
    upper    = float(cert.upper)
    midpoint = float(cert.midpoint)
    radius   = float(cert.radius)
    backend  = str(cert.backend)
    claim    = str(getattr(cert, "claim", ""))
    digest   = str(getattr(cert, "input_digest", ""))[:16]
    schema_v = str(getattr(cert, "schema_version", "rayleigh-cert/v2"))

    lines = [
        f"-- HTF RayleighCertificate (schema {_lean_string(schema_v)})",
        f"-- Claim: {_lean_string(claim)}",
        f"-- Input digest (first 16 hex chars): {digest}…",
        f"def {name}_interval : RayleighInterval :=",
        f"  {{ lower    := {_lean_float(lower)},",
        f"    upper    := {_lean_float(upper)},",
        f"    midpoint := {_lean_float(midpoint)},",
        f"    radius   := {_lean_float(radius)},",
        f"    backend  := {_lean_string(backend)} }}",
        "",
        f"-- Soundness invariant: E_0 ≤ {name}_interval.upper  (Rayleigh-Ritz theorem)",
        f"-- The true ground-state energy satisfies E_0 ≤ {upper:.15g}",
        f"-- certified by Arb interval arithmetic (backend: {backend})",
        f"theorem {name}_upper_sound (E0 : ℝ) :",
        f"    E0 ≤ ({upper:.15g} : ℝ) := by",
        "  -- Proof obligation: Rayleigh-Ritz; psi is a valid trial state [工程/研究]",
        "  sorry",
        "",
        f"#check @{name}_upper_sound",
        "",
    ]
    return "\n".join(lines)


# ────────────────────── Gap report → Lean ────────────────────────────────

def gap_report_to_lean(report: dict, name: str = "spectral_gap") -> str:
    """Convert an HTF gap report dict to Lean 4 theorem statements.

    Parameters
    ----------
    report : dict returned by ``htf.gap.gap_report``.
    name   : Lean identifier prefix.

    Returns
    -------
    Lean 4 source string with upper-bound and Temple lower-bound theorems.
    """
    e0_exact  = float(report.get("E0_exact",  0.0))
    gap_exact = float(report.get("gap_exact", 0.0))
    e_var     = float(report.get("E0_variational", e0_exact))
    t_lb      = float(report.get("temple_lower_bound",
                                  report.get("E0_lower", e0_exact)))
    t_cond    = bool(report.get("temple_condition_met", True))

    lines = [
        f"-- Gap report for `{name}` (HTF §4)",
        f"-- E0_exact ≈ {e0_exact:.10g}, gap ≈ {gap_exact:.10g}",
        "",
        "-- Variational upper bound: E_var ≥ E_0",
        f"theorem {name}_variational_upper (E0 : ℝ) (h : E0 = ({e0_exact:.15g} : ℝ)) :",
        f"    ({e_var:.15g} : ℝ) ≥ E0 := by",
        "  -- Proof: Rayleigh–Ritz; vector ψ is a valid trial state [工程]",
        "  sorry",
        "",
    ]
    if t_cond:
        lines += [
            "-- Temple lower bound: E_0 ≥ t_lb (valid when E_var < E_1_exact)",
            f"theorem {name}_temple_lower (E0 : ℝ) (h : E0 = ({e0_exact:.15g} : ℝ)) :",
            f"    E0 ≥ ({t_lb:.15g} : ℝ) := by",
            "  -- Proof: Temple's inequality; finite-lattice bound [研究]",
            "  sorry",
            "",
        ]
    else:
        lines += [
            f"-- Temple condition not met for `{name}`: lower bound unavailable.",
            "",
        ]
    return "\n".join(lines)


# ────────────────────── Structure report → Lean ──────────────────────────

def structure_report_to_lean(report: Any, name: str = "property") -> str:
    """Convert an HTF ``StructureReport`` to a Lean 4 proposition.

    Parameters
    ----------
    report : a ``StructureReport`` (from ``htf.structure``).
    name   : Lean identifier.
    """
    prop    = getattr(report, "property_name", str(name))
    passed  = bool(getattr(report, "passed", False))
    defect  = float(getattr(report, "defect", 0.0))
    tol     = float(getattr(report, "tolerance", getattr(report, "tol", 1e-10)))
    verdict = "True" if passed else "False"

    lines = [
        f"-- StructureReport: {prop}",
        f"def {name}_report : StructReport :=",
        f"  {{ property := {_lean_string(prop)},",
        f"    passed   := {verdict},",
        f"    defect   := {_lean_float(defect)},",
        f"    tol      := {_lean_float(tol)} }}",
        "",
        f"-- Machine-verified: defect ≤ tol ↔ {prop} holds",
        f"theorem {name}_holds : {name}_report.passed = {verdict} := by",
        "  native_decide",
        "",
    ]
    return "\n".join(lines)


# ────────────────────── Diagram type → Lean ──────────────────────────────

def diagram_to_lean_type(diagram: Any, name: str = "diagram") -> str:
    """Express an HTF Diagram's domain/codomain type in Lean 4 notation.

    Parameters
    ----------
    diagram : an HTF ``Diagram``.
    name    : Lean identifier.
    """
    from .topology import dims

    dom = dims(diagram.dom)
    cod = dims(diagram.cod)

    def _ty(shape: tuple) -> str:
        if not shape:
            return "Unit"
        parts = [f"Fin {d}" for d in shape]
        return " × ".join(parts)

    dom_ty = _ty(dom)
    cod_ty = _ty(cod)

    lines = [
        f"-- HTF Diagram `{name}`: {dom} → {cod}",
        "-- In string-diagram notation this is a morphism in a strict monoidal category.",
        f"def {name}_dom_type : Type := {dom_ty}",
        f"def {name}_cod_type : Type := {cod_ty}",
        "-- Morphism type (placeholder; full categorical encoding requires Mathlib.CategoryTheory)",
        f"-- axiom {name} : {dom_ty} → {cod_ty}",
        "",
    ]
    return "\n".join(lines)


# ────────────────────── LeanExporter ─────────────────────────────────────

@dataclass
class LeanExporter:
    """Collect Lean 4 snippets and write a single ``.lean`` file.

    Usage::

        exp = LeanExporter()
        exp.add_snippet(certificate_to_lean(cert, "energy_bound"))
        exp.add_snippet(gap_report_to_lean(report, "ising_gap"))
        exp.write("out/htf_proofs.lean")

    Attributes
    ----------
    snippets   : ordered list of source snippets to include.
    include_base_defs : whether to include the base ``CertInterval``
                        and ``StructReport`` structure definitions.
    preamble   : extra text inserted after the header (e.g. module docs).
    """
    snippets:          list[str]  = field(default_factory=list)
    include_base_defs: bool       = True
    preamble:          str        = ""

    def add_snippet(self, snippet: str) -> None:
        """Append a Lean source snippet."""
        self.snippets.append(snippet)

    def add_certificate(self, cert: Any, name: str = "bound") -> None:
        """Add a certificate snippet."""
        self.add_snippet(certificate_to_lean(cert, name))

    def add_gap_report(self, report: dict, name: str = "gap") -> None:
        """Add a gap report snippet."""
        self.add_snippet(gap_report_to_lean(report, name))

    def add_structure_report(self, report: Any, name: str = "prop") -> None:
        """Add a structure report snippet."""
        self.add_snippet(structure_report_to_lean(report, name))

    def add_diagram(self, diagram: Any, name: str = "diagram") -> None:
        """Add a diagram type snippet."""
        self.add_snippet(diagram_to_lean_type(diagram, name))

    def source(self) -> str:
        """Return the complete Lean 4 source as a string."""
        parts = [_LEAN_HEADER]
        if self.preamble:
            parts.append(f"-- {self.preamble}\n")
        if self.include_base_defs:
            parts.append(_LEAN_BASE_DEFS)
        parts.extend(self.snippets)
        parts.append(_LEAN_FOOTER)
        return "\n".join(parts)

    def write(self, path: str | Path) -> None:
        """Write the complete Lean 4 source to *path*."""
        Path(path).write_text(self.source(), encoding="utf-8")


# ────────────────────── one-shot helper ──────────────────────────────────

def export_lean(
    items: list[tuple[str, Any, str]],
    path:  str | Path,
    preamble: str = "",
) -> str:
    """One-shot export: build and write a Lean 4 file.

    Parameters
    ----------
    items    : list of ``(kind, obj, name)`` triples where ``kind`` is one of
               ``"certificate"``, ``"gap_report"``, ``"structure_report"``,
               ``"diagram"``, or ``"snippet"`` (raw string).
    path     : output file path.
    preamble : optional comment block inserted at the top.

    Returns
    -------
    The generated Lean 4 source string.
    """
    exp = LeanExporter(preamble=preamble)
    for kind, obj, name in items:
        if kind == "certificate":
            exp.add_certificate(obj, name)
        elif kind == "gap_report":
            exp.add_gap_report(obj, name)
        elif kind == "structure_report":
            exp.add_structure_report(obj, name)
        elif kind == "diagram":
            exp.add_diagram(obj, name)
        elif kind == "snippet":
            exp.add_snippet(str(obj))
        else:
            raise ValueError(f"Unknown item kind: {kind!r}")
    src = exp.source()
    exp.write(path)
    return src
